apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: prod
on:
  workflow_dispatch:
jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: nexus
          artifact-id: 4bfe85fc-911a-4b72-80d6-9effca576a0f
          target-environment: QA